language: android
sudo: false
jdk:
- oraclejdk8
android:
  licenses:
  - ".+"
  components:
  - platform-tools
  - tools
  - tools
  - build-tools-24.0.3
  - extra-android-support
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-24
script:
- "./gradlew build bintrayUpload --stacktrace"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
    - sqlinantes:8Usex84M6JTsUhBEymvhpm5w#team-blockchain
env:
  global:
  - secure: 1wvRauGsks4HweZQJDkzQ8KfWznJvhmtlrMI3iFmRT7p+4yMe16MP61cIXZ9oxxQ7qKwj+shW+fkabG3bLI3A2ViIVMkGSFsBbCYSm5YjWGmoMHw0n5VBWv+cWqiuVP3mzq/2tEQglIGYWQ05hPJtOOixPXy3dVr1exbzFUCDIT+GUWV5kFy815TcEkpyv4c3nI49QSFmwZqI05R0RsyMHnIArKLZlQRzzMdNQrtaNEvAlO6RkIxRKOkEjzsx/dJajjax7W8Mu6BpF/JcZj/FE6Oq2SKsJbNFI9IPJ/dnc1/SRKHWLEVzyBHxgPm4/K5nwVqDllTLJTIeiuJCjpqFABxNw3iRSoRExBAWQciuCmAnHW3sSBL1oGCJTCaelx+SA532KgDJjSPCCe/SUfmB7FdVXrEpm0zTH6QDQ5NSijHM3GN3z2Dz+TaF3D5eLpnxQ1KI3tybW2NXXn0UlLTJs+PaG5XBKXJaXx+E1UKKPz+S8fryvXrdu88tO9t0o9HF7yGFag302h4b9f2ad8DkdK22akQwVXIowiKYg21cA2uXEBZfprqQCidOejv+3piDJSJiKxOX/hh3kVrIIzFEVuxeZTip+fDj5+s3CAS8nrQZAgPcnswf83Imc2gXbxeSOWuAODUi4bqrKRe9o+HNapYeH1y0GBs6lnb/+rvK8c=
  - secure: HCU6R3bhGVPrKOaqur7RcFx0cl//AtpVVOnT4XLfYGd3nhkdsKAjPh0nl+PdTtr0Xy3nKGoTAEmcxVHRGq9IoczH29WSYw5W0bElH1tFFqxyz6KCPIHBGmVAK9pMjDB99G4TT7YmrqD94j5Q4qDiytSGZEQl7DrxS2g18MSZr5XYBUrCJdfsdVViVrTx28EUA7WP6ovc+yM3BANSq/8v5P2wfoIAYUpoWl8IyacMmUZwuNcPz91Krf6j7llxW0/dE+Q8zXRVR7jesyYrOw3LyBT0wQldhJPyD3v+k5g1LtwNxt6ziM5iYBv1pUYNExvpvbS5+UbLVYpkkBR90s/5F6tl1m2SbODwSdcOVKMwy4/chtljDyZ5sgijBcAxyT66whKeo2P+gbtsXgsY6Jsz4pqtqNXQgeDAac7ZKuCsIjLhECwIplveZpOzqsf8VehERG1hWh0YiMjRhtZpVVYqkT4X4G7VBarsGZ73gP/FAoQMKVzT+x8wH2ZXyrFMrBUueyIDqiSH6JJz74JGpnq/b9E3ufwW21mkUaZrxHB8nwJ2Rbt6YLAiYSzjTYsqQWLhWEMpN27JOfm47xQ1inW5NpFu3nSGL1YPza5iGeHnGYSztOa2k+9aueWuz8l0k26ml+qF8L9tPuYLqKlzOmx7878zYxGxc05QRgCWmAsTKQY=
  - secure: gC2lZWIvtjDnAqQNUalfMLZH+urTPImzKnh7nGZwwVpBcfdQU1JNsYZc8N4RbPFHoeE/ZDOf8GySEAUSE3C9zp039qaY1BklRM3AkDwO5sWD/AkxiCq57as3oIGywslsdTzqME3/kR07gWn3gqrBr1fgW5JBetLLuAYoQhzqIOS5wm/wD36C3u3U3i0R+/LD77nQm39s5NSmltYi0VawVNE1q3BE3RejMtqEyupIg0C2By6bo3Z48iTTX6CREmQoNuHoSXyWq8tv6hWhf8BMsYsakf/zMGmccYIQjsYT3CohDqAp2wAqm6nM5x92eXiRgQoXu3dhiHjXdcI1fUY5BAbwtAXsb0Sh1Wy0Yj4pK5Q+bnL1ZrWuSOpzjWK/8N7Pfgtqqt5CYqFvpvD5ARiNEfG9MLMhdZ9s7UEoigs2qg6aWLheVIwE8QWrOIgul+WQ29dUApZajQ37afLV41zcV/TYrmeeurb/ybTb03qSOH500Tmt651qLn/N7Ckv47jIeGu0OD+LOqkz6f5KvoLVL4w1R5D8sh5yEYzaRFxJd89T1agwVG2vzvl6PVCOXtIXKrprYqthASeC0HBJwSeuIqeLHR8mN5gf9tN4iKyq20nwmaspoo3/YTPquGdWxhOeJy3sNxT3YdqiVFIQOuwdOCvtWeBHDdyb65QkLHEhHs8=
  - secure: 0xhzSWz9I390kJg/1Bxz1zic1wPW9Gh0eMTo01CZDK31m8ZLHzYc3oDeiI7woxieKk9ZqFXEZqHWe6tRagqq2V2Jf8XGnc3X04VtdK7jsNyfbfEcsu7wIPIlkovHXwbAkFUOXGF3KXK334aO71Nfjvh5H84f2F4XjeetMyywhHUgeFt9uHM61EvTNR9td1WOhW4fMw6scT1/iN+2vi2b65WbD1INrGR/o3HI+l6+gLwc6JQlTN4XYW3f4MGE5VBC/6ZVMhZ8UOoGSfo9sNLVdLeP96q0DllvPQMcWnN8lPoqrwUn7pBZZQDP/WaMEsV3eFm5AorPPAWlRJgXuSIE+FoyckaHAPqDblw6w3zHAqZqFSrvTYtyz+vgP29+pOQfeL3xj1T+emzTsA22rm03zdE9ph4/x8lss8qL5cpay9toMicNntNCEty7MWcNdO2Iy6cwM0QT3nsJz/6/nMEQC/Doj2vTdZsSB9Yl/b0neMcYKxQ9YKVHOUkirqMqTkLI4lWNUcjnGxk6nr4CTIBE+z4d+HlG9hrWQrJwkvJ7GhmKYO0osNZtkYaIMqqn7xHCR166f0z9T0RtEm8Y3DWIP47R0H5ZRmvVdOK4iDz2eU4UJmYdXd5GU4XPB/SecviclOgk+Zu0d0YFRmXsqfIiQFn/U/TGA0oMWumJ/ZBzwgg=
